"""PDF audit report export (reportlab)."""
from __future__ import annotations

import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

BRAND = colors.HexColor("#1d4ed8")  # blue-700
SLATE = colors.HexColor("#334155")
LIGHT = colors.HexColor("#f1f5f9")


def _styles():
    base = getSampleStyleSheet()
    s = {
        "title": ParagraphStyle("t", parent=base["Title"], fontName="Helvetica-Bold",
                                fontSize=20, textColor=BRAND, spaceAfter=2),
        "sub": ParagraphStyle("s", parent=base["Normal"], fontSize=10, textColor=SLATE),
        "h": ParagraphStyle("h", parent=base["Heading2"], fontName="Helvetica-Bold",
                            fontSize=13, textColor=BRAND, spaceBefore=10, spaceAfter=4),
        "body": ParagraphStyle("b", parent=base["Normal"], fontSize=9.5, leading=13,
                               textColor=SLATE),
        "small": ParagraphStyle("sm", parent=base["Normal"], fontSize=8, textColor=SLATE),
        "cell": ParagraphStyle("c", parent=base["Normal"], fontSize=8.5, leading=11,
                               textColor=colors.black),
    }
    return s


def _table(rows, widths, header=True):
    t = Table(rows, colWidths=widths, repeatRows=1 if header else 0)
    style = [
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]
    if header:
        style += [("BACKGROUND", (0, 0), (-1, 0), BRAND),
                  ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                  ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")]
    for i in range(1, len(rows)):
        if i % 2 == 0:
            style.append(("BACKGROUND", (0, i), (-1, i), LIGHT))
    t.setStyle(TableStyle(style))
    return t


def export_report(out_path: str, title: str, contract: str, queries: list[dict],
                  algorithm_results: list[dict] | None = None) -> str:
    """queries: list of {name, description, rows, columns}."""
    S = _styles()
    doc = SimpleDocTemplate(out_path, pagesize=A4,
                            leftMargin=16 * mm, rightMargin=16 * mm,
                            topMargin=14 * mm, bottomMargin=14 * mm)
    flow = []
    flow.append(Paragraph("AuditGraph", S["title"]))
    flow.append(Paragraph(f"Vulnerability knowledge-graph report &mdash; generated "
                          f"{datetime.date.today().isoformat()} by AuditGraph (FalkorDB)", S["sub"]))
    flow.append(Spacer(1, 6))
    flow.append(HRFlowable(width="100%", thickness=1, color=BRAND))
    flow.append(Spacer(1, 8))
    flow.append(Paragraph(f"Target: <b>{contract}</b>", S["body"]))
    flow.append(Spacer(1, 4))

    for q in queries:
        flow.append(Paragraph(q["name"], S["h"]))
        if q.get("description"):
            flow.append(Paragraph(q["description"], S["small"]))
            flow.append(Spacer(1, 3))
        cols = q.get("columns") or []
        if not cols:
            flow.append(Paragraph("No results.", S["body"]))
            flow.append(Spacer(1, 6))
            continue
        header = [Paragraph(c, S["cell"]) for c in cols]
        rows = [header]
        for r in q["rows"][:60]:
            rows.append([Paragraph(str(v) if v is not None else "&mdash;", S["cell"]) for v in r])
        n_cols = len(cols)
        w = 178 * mm / n_cols
        flow.append(_table(rows, [w] * n_cols))
        flow.append(Spacer(1, 8))

    if algorithm_results:
        flow.append(Paragraph("Graph algorithms", S["h"]))
        for a in algorithm_results:
            algo = a.get("algorithm", "algorithm")
            flow.append(Paragraph(f"<b>{algo}</b>", S["body"]))
            for node in a.get("nodes", [])[:10]:
                flow.append(Paragraph(
                    f"&bull; {node.get('name')} ({node.get('label')}) &mdash; score {node.get('score')}",
                    S["small"]))
            path = a.get("path")
            if path:
                flow.append(Paragraph("path: " + " &rarr; ".join(path), S["small"]))
            flow.append(Spacer(1, 5))

    flow.append(Spacer(1, 10))
    flow.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1")))
    flow.append(Spacer(1, 4))
    flow.append(Paragraph(
        "Generated by AuditGraph. Data sources: SWC registry, public exploit post-mortems, "
        "Etherscan metadata, and Slither static analysis. Not a substitute for a manual audit.",
        S["small"]))
    doc.build(flow)
    return out_path
